import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link';

// import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <header className="container">
      <div className="page-header">
        <div className="logo">
          <a href="'/img/img2.jpg'">Logo.</a>

        </div>
        <input type="checkbox" id="click" />

        <label htmlFor="click" className="mainicon">
          <div className="menu">
            <i className="bx bx-menu"></i>
          </div>
        </label>
        <ul>
        <li><Link href={"/"}>Home</Link></li>
        <li><Link href="/route/1">Blog</Link></li>
          <li><Link href={"/contact"}>Contact</Link></li>
        </ul>
      </div>
    </header>
        
        {children}</body>
    </html>
  )
}
